### ISSUE TITLE
Drag and drop sometimes freezes scoot

### ISSUE THREAD

**Issue by vultix** [mjrusso/scoot#32] opened 2022-10-16 21:25 UTC
First off, thank you for the useful tool! It's absolutely brilliant.

In some context, drag and drop works great.  For instance, dragging files around in Finder.  In other cases, the grid disappears as soon as i hit the `=` key.  Opening the grid again with `Cmd-shift-k` freezes the application, requiring manually using the mouse to click away.

Contexts that break scoot:
- Dragging windows using their title bar (such as trying to re-position a terminal window)
- Trying to reorder chrome tabs

### Steps to reproduce:
- Open scoot grid `Cmd-shift-k`
- Position your cursor over a window title bar
- Press `=`

Observe that the grid is hidden now.  Attempting to reopen it yields an unresponsive scoot grid

**Comment by mjrusso** [comment] 2022-12-03 14:15
@vultix thank you for the kind words and for the very detailed bug report!

> In other cases, the grid disappears as soon as i hit the `=` key. 

I'm able to reproduce this issue with tabs in Safari and Chrome. 

My hunch here is that the grid disappearance is related to the hackery described in #28.

(I also tested dragging and dropping tabs in Firefox and Finder; sometimes the OS rejects the input entirely, but sometimes I'm actually able to drag and drop tabs. Very strange.)

> Opening the grid again with `Cmd-shift-k` freezes the application, requiring manually using the mouse to click away.

This I'm not able to reproduce (at least right now; I'm on Ventura). I have occasionally seen Scoot hang, however I've never been able to reliably reproduce. 

Do you happen to be running Ventura now? If so, are you able to reproduce the freeze?

**Comment by mjrusso** [comment] 2022-12-10 18:22
The issue with grid disappearance is fixed in [v1.2](https://github.com/mjrusso/scoot/releases/tag/v1.2) (see #28), and likely the hanging too (but please let me know if that isn't the case).

**Closed by mjrusso** 2022-12-10 18:22 UTC
